# erp_mock/erp_connector.py
# PURPOSE: Client that connects AgentProcure to the mock ERP API.
# In production this would point to real SAP/Oracle endpoints.
#
# Usage:
#   from erp_mock.erp_connector import ERPConnector
#   erp = ERPConnector()
#   bom = erp.fetch_bom("BOM-2024-001")
#   pr  = erp.create_pr(recommendations, bom_id="BOM-2024-001")

import requests
import pandas as pd
from datetime import date, timedelta

ERP_BASE_URL = "http://localhost:8000/api"


class ERPConnector:
    """
    Client for AgentProcure ↔ ERP communication.
    Wraps all HTTP calls in clean Python methods.
    """

    def __init__(self, base_url=ERP_BASE_URL):
        self.base_url = base_url
        self.connected = False

    def check_connection(self):
        """Returns True if ERP API is reachable."""
        try:
            resp = requests.get(f"{self.base_url}/health", timeout=3)
            self.connected = resp.status_code == 200
            return self.connected, resp.json()
        except Exception as e:
            self.connected = False
            return False, {"error": str(e)}

    def fetch_bom(self, bom_id: str) -> pd.DataFrame:
        """
        Fetches a BOM from ERP and returns it as a DataFrame
        ready to upload directly into AgentProcure's BOM input.
        """
        resp = requests.get(f"{self.base_url}/bom/{bom_id}", timeout=10)
        resp.raise_for_status()
        data = resp.json()

        rows = []
        for item in data['items']:
            rows.append({
                'part_no':           item['part_no'],
                'quantity_required': item['quantity'],
                'target_price':      item.get('target_price', None),
                'preferred_supplier': None
            })
        return pd.DataFrame(rows)

    def list_boms(self):
        """Lists all BOMs available in the ERP system."""
        resp = requests.get(f"{self.base_url}/bom", timeout=10)
        resp.raise_for_status()
        return resp.json()['boms']

    def create_pr(self, recommendations: list, bom_id: str,
                  requester: str = "AgentProcure System",
                  scenario: str = "balanced") -> dict:
        """
        Writes AgentProcure's sourcing recommendations back to ERP
        as a Purchase Requisition.

        Args:
            recommendations: list of dicts from Module 5 output
            bom_id:          str — ERP BOM reference
            requester:       str — username submitting the PR
            scenario:        str — which Pareto scenario was used

        Returns:
            dict with pr_number, status, message
        """
        delivery_date = str(date.today() + timedelta(days=45))

        line_items = []
        total_value = 0.0

        for rec in recommendations:
            line_items.append({
                "part_no":              rec['part_no'],
                "quantity":             int(rec.get('quantity_required', 1)),
                "recommended_supplier": rec['recommended_supplier'],
                "unit_price":           float(rec['landed_cost']),
                "currency":             "USD",
                "delivery_date":        delivery_date
            })
            total_value += float(rec.get('line_value', 0))

        payload = {
            "bom_id":      bom_id,
            "requester":   requester,
            "plant":       "PLANT-IN-01",
            "priority":    "Normal",
            "scenario":    scenario,
            "line_items":  line_items,
            "total_value": round(total_value, 2),
            "notes":       f"Auto-generated by AgentProcure | Scenario: {scenario}"
        }

        resp = requests.post(
            f"{self.base_url}/purchase_requisition",
            json=payload,
            timeout=15
        )
        resp.raise_for_status()
        return resp.json()

    def get_pr(self, pr_number: str) -> dict:
        """Retrieves a specific PR from ERP."""
        resp = requests.get(
            f"{self.base_url}/purchase_requisition/{pr_number}",
            timeout=10
        )
        resp.raise_for_status()
        return resp.json()

    def list_prs(self) -> list:
        """Lists all PRs created this session."""
        resp = requests.get(
            f"{self.base_url}/purchase_requisitions",
            timeout=10
        )
        resp.raise_for_status()
        return resp.json()['purchase_requisitions']

    def get_erp_suppliers(self) -> pd.DataFrame:
        """Fetches supplier master from ERP as DataFrame."""
        resp = requests.get(f"{self.base_url}/suppliers", timeout=10)
        resp.raise_for_status()
        return pd.DataFrame(resp.json()['suppliers'])


# ─────────────────────────────────────────────
# STANDALONE TEST
# ─────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "="*55)
    print("  ERP Connector Test")
    print("  Make sure mock_erp_api.py is running first!")
    print("="*55)

    erp = ERPConnector()

    # 1. Health check
    print("\n1. Checking ERP connection...")
    ok, info = erp.check_connection()
    if not ok:
        print(f"  ❌ ERP not reachable: {info}")
        print("  Start it with: python3 erp_mock/mock_erp_api.py")
        exit(1)
    print(f"  ✅ Connected: {info['service']}")

    # 2. List BOMs
    print("\n2. Fetching available BOMs from ERP...")
    boms = erp.list_boms()
    for b in boms:
        print(f"  {b['bom_id']}: {b['description']} ({b['item_count']} items)")

    # 3. Fetch first BOM as DataFrame
    print("\n3. Fetching BOM-2024-001 as DataFrame...")
    bom_df = erp.fetch_bom("BOM-2024-001")
    print(f"  {len(bom_df)} parts ready for AgentProcure analysis:")
    print(bom_df.to_string(index=False))

    # 4. Simulate creating a PR
    print("\n4. Creating mock Purchase Requisition...")
    mock_recs = [
        {'part_no':'MAG-CORE-ETD39','recommended_supplier':'Shanghai Electronics Ltd',
         'landed_cost':1.35,'line_value':675.0,'quantity_required':500},
        {'part_no':'ASM-XFMR-LVCT','recommended_supplier':'Chennai Precision Parts',
         'landed_cost':20.20,'line_value':2020.0,'quantity_required':100},
    ]
    pr = erp.create_pr(mock_recs, "BOM-2024-001", "nikhil@company.com", "balanced")
    print(f"  ✅ PR Created: {pr['pr_number']}")
    print(f"  Status:       {pr['status']}")
    print(f"  Total Value:  ${pr['total_value']:,.2f}")
    print(f"  Message:      {pr['message']}")

    # 5. List all PRs
    print("\n5. All Purchase Requisitions in ERP:")
    prs = erp.list_prs()
    for p in prs:
        print(f"  {p['pr_number']} | ${p['total_value']:,.2f} | {p['status']}")

    print(f"\n✅ ERP integration test complete!\n")